[global]
    checkNewVersion = false
    sendAnonymousUsage = false

# TODO: remove this later
[log]
    level = "TRACE"

# TODO: remove this later
[accessLog]

[[tls.certificates]]
    certFile = "/etc/ssl/certs/cert.pem"
    keyFile = "/etc/ssl/private/key.pem"

# add entry points from which services will be accessible
[entryPoints]
    [entryPoints.websecure]
        address = ":2009"

# Proxy upstream
[http.services]
    [http.services.proxy.loadBalancer]
        [[http.services.proxy.loadBalancer.servers]]
            url = "http://proxy:8888/"

# This file provider is used to read in the traefik.toml file
# so routers and middlewares are available. This is strange
[providers.file]
    filename = "/etc/traefik/traefik.toml"

# This router is only used to run the forward-auth
# middleware. It does nothing else
[http.routers]
    [http.routers.auth-router]
        entrypoints = ["websecure"]
        middlewares = ["strip-versionprefix", "forward-auth@file"]
        rule = "PathPrefix(`/v0`)"
        service = "proxy@file"
        [http.routers.auth-router.tls]

# forward auth middleware to check access
[http.middlewares]
    [http.middlewares.forward-auth.forwardauth]
        address = "http://cyphernodeadmin:3032/gatekeeper"
        authResponseHeaders = ["X-Forwarded-User"]
        trustForwardHeader = true

    [http.middlewares.strip-versionprefix.stripprefix]
        prefixes=["/v0","/v0/","/v1","/v1/"]
        forceSlash=true

